```plantuml
@startuml
queue "vedtak.json" <<topic>> as vedtak_json
queue "soknad-leftjoin-vedtak-repartition" <<topic>> as soknad_leftjoin_vedtak_repartition
queue "medlem-join-vedtak-repartition" <<topic>> as medlem_join_vedtak_repartition
queue "soknad.json" <<topic>> as soknad_json
queue "medlem.json" <<topic>> as medlem_json
package "Sub-topology: 0" {
	database "vedtak-store" <<State Store>> as vedtak_store
	agent "soknad-leftjoin-vedtak-repartition-source" <<Source>> as soknad_leftjoin_vedtak_repartition_source
	agent "medlem-join-vedtak-repartition-source" <<Source>> as medlem_join_vedtak_repartition_source
	agent "soknad-leftjoin-vedtak" <<Processor>> as soknad_leftjoin_vedtak
	agent "ignore-existing-vedtak" <<Processor>> as ignore_existing_vedtak
	agent "medlem-join-vedtak" <<Processor>> as medlem_join_vedtak
	agent "add-medlem" <<Processor>> as add_medlem
	agent "create-vedtak" <<Processor>> as create_vedtak
	agent "KSTREAM-SOURCE-0000000000" <<Source>> as KSTREAM_SOURCE_0000000000
	agent "log-produced-log-produce-created-json-vedtak" <<Processor>> as log_produced_log_produce_created_json_vedtak
	agent "log-produced-log-produce-json-vedtak-with-medlem" <<Processor>> as log_produced_log_produce_json_vedtak_with_medlem
	agent "KTABLE-SOURCE-0000000001" <<Processor>> as KTABLE_SOURCE_0000000001
	agent "produce-created-json-vedtak" <<Sink>> as produce_created_json_vedtak
	agent "produce-json-vedtak-with-medlem" <<Sink>> as produce_json_vedtak_with_medlem
	soknad_leftjoin_vedtak_repartition --> soknad_leftjoin_vedtak_repartition_source
	medlem_join_vedtak_repartition --> medlem_join_vedtak_repartition_source
	vedtak_store -- soknad_leftjoin_vedtak
	vedtak_store -- medlem_join_vedtak
	vedtak_json --> KSTREAM_SOURCE_0000000000
	vedtak_store -- KTABLE_SOURCE_0000000001
	vedtak_json <-- produce_created_json_vedtak
	vedtak_json <-- produce_json_vedtak_with_medlem
	soknad_leftjoin_vedtak_repartition_source --> soknad_leftjoin_vedtak
	medlem_join_vedtak_repartition_source --> medlem_join_vedtak
	soknad_leftjoin_vedtak --> ignore_existing_vedtak
	ignore_existing_vedtak --> create_vedtak
	medlem_join_vedtak --> add_medlem
	add_medlem --> log_produced_log_produce_json_vedtak_with_medlem
	create_vedtak --> log_produced_log_produce_created_json_vedtak
	KSTREAM_SOURCE_0000000000 --> KTABLE_SOURCE_0000000001
	log_produced_log_produce_created_json_vedtak --> produce_created_json_vedtak
	log_produced_log_produce_json_vedtak_with_medlem --> produce_json_vedtak_with_medlem
}
package "Sub-topology: 1" {
	agent "consume-json-soknad" <<Source>> as consume_json_soknad
	agent "log-consumed-json-soknad" <<Processor>> as log_consumed_json_soknad
	agent "select-key_soknad.personident" <<Processor>> as select_key_soknad_personident
	agent "soknad-leftjoin-vedtak-repartition-filter" <<Processor>> as soknad_leftjoin_vedtak_repartition_filter
	agent "soknad-leftjoin-vedtak-repartition-sink" <<Sink>> as soknad_leftjoin_vedtak_repartition_sink
	soknad_json --> consume_json_soknad
	soknad_leftjoin_vedtak_repartition <-- soknad_leftjoin_vedtak_repartition_sink
	consume_json_soknad --> log_consumed_json_soknad
	log_consumed_json_soknad --> select_key_soknad_personident
	select_key_soknad_personident --> soknad_leftjoin_vedtak_repartition_filter
	soknad_leftjoin_vedtak_repartition_filter --> soknad_leftjoin_vedtak_repartition_sink
}
package "Sub-topology: 2" {
	agent "consume-json-medlem" <<Source>> as consume_json_medlem
	agent "log-consumed-json-medlem" <<Processor>> as log_consumed_json_medlem
	agent "select-key_medlem.personident" <<Processor>> as select_key_medlem_personident
	agent "medlem-join-vedtak-repartition-filter" <<Processor>> as medlem_join_vedtak_repartition_filter
	agent "medlem-join-vedtak-repartition-sink" <<Sink>> as medlem_join_vedtak_repartition_sink
	medlem_json --> consume_json_medlem
	medlem_join_vedtak_repartition <-- medlem_join_vedtak_repartition_sink
	consume_json_medlem --> log_consumed_json_medlem
	log_consumed_json_medlem --> select_key_medlem_personident
	select_key_medlem_personident --> medlem_join_vedtak_repartition_filter
	medlem_join_vedtak_repartition_filter --> medlem_join_vedtak_repartition_sink
}
@enduml
```